### ISSUE TITLE
Display of avatar on dashboard is broken after reload

### ISSUE THREAD

**Issue by birthe** [eneiluj/integration_openproject#1]
On the dashboard the OpenProject avatar is not displayed correctly after an update of the page.
<img width="1503" alt="OpenProject-integration" src="https://user-images.githubusercontent.com/2813966/115544153-8a158580-a2a2-11eb-80b4-1645346bac04.PNG">

> Tested on Nexcloud 20 with OP integration activated
> FireFox 88.0 (64-bit)

**Comment by eneiluj** [comment]
Thanks for the feedback!

I can't reproduce the issue but I made a new release (v1.0.2) with cleaner avatar image responses (with the mime type and a different response type).

Could you try v1.0.2?
If the issue persists, could you check if there is any related error in nextcloud.log?

It would also be interesting to know what the browser really gets. You can see that in the browser network tool (F12 -> Network tab). Reload the dashboard page and filter the results with "avatar". Are the requests failing?

**Comment by birthe** [comment]
Network status looks ok:
![image](https://user-images.githubusercontent.com/2813966/116059869-9c683880-a681-11eb-9d1d-522cdba1f9d2.png)
Still the problem occurs. 
I am testing with Nextcloud 20 - maybe this causes the issue? Is the update to 1.0.2. there available as well?
Thank you

**Comment by eneiluj** [comment]
I couldn't reproduce the issue in NC 20 either.

Yes v1.0.2 is available for NC 20 and 21. It takes a few minutes to appear in the app settings. It should be possible to update the app by now.

About the issue itself, is it always working when you get to the dashboard page and then always failing when you reload it?

**Comment by birthe** [comment]
It's still not working after the update. 
Yey, it first appears correctly on the dashbaord and then, after update or reload, the avatars disappear.

**Comment by eneiluj** [comment]
Did you try with a different browser or on a different system? I tried with FF and chromium on GNU/Linux and windows. Still can't reproduce the issue :grin:.

**Comment by birthe** [comment]
I tested FF and Chrome on Windows. Same results.

**Comment by eneiluj** [comment]
Ok this should be fixed with v1.0.4. Is it? :grin:

Could you actually check both cases:
* when an avatar is manually set in OP settings
* when it's not and the gravatar one is used (is it actually displayed in NC dashboard?)

**Comment by birthe** [comment]
Firefox works as expected now. 👍 Tested without any avatar, with custom avatar (manually set) and with gravatar. All are displayed correctly, also after update.

I still get issues with Chrome:
With custom avatar, the fallback avatar is shown for your account (even though you set a custom avatar). For me, nothing is displayed. Same with gravatar.
![bug-chrome](https://user-images.githubusercontent.com/2813966/116289150-85653b80-a792-11eb-8eea-219d551496e0.PNG)

**Comment by eneiluj** [comment]
Hmmm there should not be much difference between those 2 browsers in terms of image loading. To make sure you reload without using the browser cache, press CTRL+F5. Does it change anything?

**Comment by birthe** [comment]
That's it! I cleared the browser cache and now it works well in all scenarios! 😅 Thanks a lot for your assistance.
